# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzurePipeline-conn'
    subscriptionId: '1499b71c-014c-461a-b22d-9bc58d06148a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzurePipeline-rg'
    location: 'West US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName azurePipeline -linkedTemplateUri https://raw.githubusercontent.com/brandonBuster/azure-pipeline/main/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'